import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import SlidingLabelInput from '../../components/common/SlidingLabelInput';
import SlidingLabelSelect from '../../components/common/SlidingSelect';
import SlidingColorInput from '../../components/common/SlidingColorInput';
import ToggleSwitch from '../../components/common/ToggleSwitch';
import BorderedFieldset from '../../components/common/BorderedFieldset';
import Card from '../../components/common/Card';
import HeadingHeader from '../../components/common/HeadingHeader';
import { useMutationApi, useGetApi } from '../../utils/useApi';
import ApiConfig from '../../config/ApiConfig';
import { Icon } from '@iconify/react';
import Pop from '../../components/common/pop';

const AddPlan = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  // Determine if we're in edit mode based on URL parameter
  const isEditMode = Boolean(id);
  const planId = id;
  
  // Single variable to handle all edit mode logic
  const isEditing = isEditMode;
  
  // Fetch plan data when in edit mode
  const { data: planDataFromApi, isLoading: planLoading, error: planError } = useGetApi({
    key: "plan"+planId,
    url: `${ApiConfig.PLAN_GET_BY_ID}/${planId}`,
    requireAuth: true,
    options: {
      enabled: isEditMode && Boolean(planId)
    }
  });

  
  const [planData, setPlanData] = useState({
    name: "",
    code: "",
    category: "",
    status: true,
    description: "",
    offerPrice: 0,
    billingCycle: "",
    gst: 0,
    maxStudent: 0,
    maxStaffUser: 0,
    storageLimit: "",
    emailNotification: true,
    smsAlerts: true,
    whatsappAlerts: true,
    customeLogoBranding: true,
    duration: "",
    termsAndPolicy: "",
    adminNotes: "",
    modules: [],
    // Visual Fields
    icon: "",
    iconColor: "#3B82F6",
    planPros: [],
    planCons: [],
    // Flexible Plan Fields
    perStudentPrice: 0,
    minStudentLimit: 0,
    maxStudentLimit: 0,
    creditCarryForward: false,
  });

  const [selectedModules, setSelectedModules] = useState([]);
  const [prosInput, setProsInput] = useState("");
  const [consInput, setConsInput] = useState("");
  const [totalPrice, setTotalPrice] = useState(0);
  const [autoGeneratedPros, setAutoGeneratedPros] = useState([]);
  const [autoGeneratedCons, setAutoGeneratedCons] = useState([]);


  // Update form data when API data is fetched (for URL-based edit mode)
  useEffect(() => {
    if (isEditMode && planDataFromApi?.data) {
      const editData = planDataFromApi.data;
      
      setPlanData({
        name: editData.name || "",
        code: editData.code || "",
        category: editData.category || "",
        status: editData.status !== undefined ? editData.status : true,
        description: editData.description || "",
        offerPrice: editData.offerPrice || 0,
        billingCycle: editData.billingCycle || "",
        gst: editData.gst || 0,
        maxStudent: editData.maxStudent || 0,
        maxStaffUser: editData.maxStaffUser || 0,
        storageLimit: editData.storageLimit || "",
        // Toggle switches - properly handle false values
        emailNotification: editData.emailNotification !== undefined ? editData.emailNotification : true,
        smsAlerts: editData.smsAlerts !== undefined ? editData.smsAlerts : true,
        whatsappAlerts: editData.whatsappAlerts !== undefined ? editData.whatsappAlerts : true,
        customeLogoBranding: editData.customeLogoBranding !== undefined ? editData.customeLogoBranding : true,
        duration: editData.duration || "",
        termsAndPolicy: editData.termsAndPolicy || "",
        adminNotes: editData.adminNotes || "",
        modules: editData.modules ? editData.modules.map(m => m.id || m) : [],
        // Visual Fields
        icon: editData.icon || "",
        iconColor: editData.iconColor || "#3B82F6",
        planPros: editData.planPros || [],
        planCons: editData.planCons || [],
        // Flexible Plan Fields
        perStudentPrice: editData.perStudentPrice || 0,
        minStudentLimit: editData.minStudentLimit || 0,
        maxStudentLimit: editData.maxStudentLimit || 0,
        creditCarryForward: editData.creditCarryForward !== undefined ? editData.creditCarryForward : false,
      });
      
      // Update selected modules
      if (editData.modules) {
        setSelectedModules(editData.modules);
      }
    }
  }, [isEditMode, planDataFromApi]);


  // Fetch modules
  const { data: modulesData, isLoading: modulesLoading } = useGetApi({
    key: "Module",
    url: ApiConfig.MODULE_GET_ALL,
    requireAuth: true,
  });

  const addPlanMutation = useMutationApi({
    key:"plans",
    url: isEditing ? ApiConfig.PLAN_UPDATE : ApiConfig.PLAN_CREATE,
    method: isEditing ? "PATCH" : "POST",
    requireAuth: true,
    options: {
      onSuccess: (data) => {
        Pop("success", isEditing ? "Plan updated successfully!" : "Plan created successfully!");
        console.log(isEditing ? "Plan updated successfully:" : "Plan created successfully:", data);
        if (isEditing) {
          // Redirect to manage plans page after successful update
          navigate('/plans/manage');
        }
        // Reset form or redirect
        setPlanData({
          name: "",
          code: "",
          category: "",
          status: true, // Reset to active (true)
          description: "",
          offerPrice: 0,
          billingCycle: "",
          gst: 0,
          maxStudent: 0,
          maxStaffUser: 0,
          storageLimit: "",
          emailNotification: true,
          smsAlerts: true,
          whatsappAlerts: true,
          customeLogoBranding: true,
          duration: "",
          termsAndPolicy: "",
          adminNotes: "",
          modules: [],
          icon: "",
          iconColor: "#3B82F6",
          planPros: [],
          planCons: [],
          perStudentPrice: 0,
          minStudentLimit: 0,
          maxStudentLimit: 0,
          creditCarryForward: false,
        });
        setSelectedModules([]);
        setTotalPrice(0);
      },
      onError: (error) => {
        console.error("Error creating plan:", error);
      },
    },
  });

  const handleChange = (field, value) => {
    setPlanData((prev) => ({ ...prev, [field]: value }));
  };

  const handleModuleSelect = (moduleId) => {
    const modulee = modulesData?.data?.find(m => m.id === moduleId);
    if (modulee && !selectedModules.find(m => m.id === moduleId)) {
      setSelectedModules(prev => [...prev, modulee]);
      setPlanData(prev => ({
        ...prev,
        modules: [...prev.modules, moduleId]
      }));
    }
  };

  console.log(selectedModules);

  // Generate automated pros and cons based on modules and plan type
  const generateAutomatedProsAndCons = () => {
    if (!modulesData?.data) return;

    const allModules = modulesData.data;
    const selectedModuleIds = selectedModules.map(m => m.id);
    
    // Generate pros for selected modules
    const modulePros = selectedModules.map(module => {
      const moduleName = module.name || 'Module';
      const moduleDesc = module.description || '';
      
      // Create pros based on module name and description
      if (moduleName.toLowerCase().includes('attendance')) {
        return `Automated attendance tracking with ${moduleDesc || 'real-time monitoring'}`;
      } else if (moduleName.toLowerCase().includes('exam')) {
        return `Comprehensive exam management system with ${moduleDesc || 'automated grading'}`;
      } else if (moduleName.toLowerCase().includes('fee')) {
        return `Complete fee management with ${moduleDesc || 'online payment integration'}`;
      } else if (moduleName.toLowerCase().includes('staff')) {
        return `Advanced staff management with ${moduleDesc || 'role-based access control'}`;
      } else if (moduleName.toLowerCase().includes('homework')) {
        return `Digital homework system with ${moduleDesc || 'assignment tracking'}`;
      } else if (moduleName.toLowerCase().includes('report')) {
        return `Detailed reporting system with ${moduleDesc || 'analytics dashboard'}`;
      } else if (moduleName.toLowerCase().includes('dashboard')) {
        return `Interactive dashboard with ${moduleDesc || 'real-time insights'}`;
      } else {
        return `Access to ${moduleName} module with ${moduleDesc || 'full functionality'}`;
      }
    });

    // Generate cons for unselected modules
    const unselectedModules = allModules.filter(m => !selectedModuleIds.includes(m.id));
    const moduleCons = unselectedModules.map(module => {
      const moduleName = module.name || 'Module';
      
      if (moduleName.toLowerCase().includes('attendance')) {
        return `No automated attendance tracking`;
      } else if (moduleName.toLowerCase().includes('exam')) {
        return `Limited exam management capabilities`;
      } else if (moduleName.toLowerCase().includes('fee')) {
        return `Basic fee management only`;
      } else if (moduleName.toLowerCase().includes('staff')) {
        return `Limited staff management features`;
      } else if (moduleName.toLowerCase().includes('homework')) {
        return `No digital homework system`;
      } else if (moduleName.toLowerCase().includes('report')) {
        return `Basic reporting only`;
      } else if (moduleName.toLowerCase().includes('dashboard')) {
        return `Limited dashboard functionality`;
      } else {
        return `${moduleName} not included`;
      }
    });

    // Add plan type specific pros and cons
    const planTypePros = [];
    const planTypeCons = [];

    if (planData.category === 'Flexible') {
      planTypePros.push('Pay only for what you use');
      planTypePros.push('Scalable pricing based on student count');
      planTypePros.push('Flexible billing options');
      planTypeCons.push('Variable monthly costs');
      if (planData.creditCarryForward) {
        planTypePros.push('Unused credits carry forward');
      } else {
        planTypeCons.push('No credit carry forward');
      }
    } else if (planData.category === 'Fixed') {
      planTypePros.push('Fixed monthly pricing');
      planTypePros.push('Predictable costs');
      planTypePros.push('All features included');
      planTypeCons.push('Higher upfront cost');
      planTypeCons.push('May pay for unused features');
    }

    // Add notifications & branding specific pros and cons
    const notificationPros = [];
    const notificationCons = [];

    if (planData.emailNotification) {
      notificationPros.push('Email notifications enabled for important updates');
    } else {
      notificationCons.push('No email notifications');
    }

    if (planData.smsAlerts) {
      notificationPros.push('SMS alerts for instant notifications');
    } else {
      notificationCons.push('No SMS alerts available');
    }

    if (planData.whatsappAlerts) {
      notificationPros.push('WhatsApp alerts for seamless communication');
    } else {
      notificationCons.push('No WhatsApp alerts available');
    }

    if (planData.customeLogoBranding) {
      notificationPros.push('Custom logo branding for professional appearance');
    } else {
      notificationCons.push('No custom logo branding');
    }

    setAutoGeneratedPros([...modulePros, ...planTypePros, ...notificationPros]);
    setAutoGeneratedCons([...moduleCons, ...planTypeCons, ...notificationCons]);
  };

  // Update automated pros/cons when modules, plan type, or notification settings change
  useEffect(() => {
    generateAutomatedProsAndCons();
  }, [
    selectedModules, 
    planData.category, 
    planData.creditCarryForward, 
    planData.emailNotification,
    planData.smsAlerts,
    planData.whatsappAlerts,
    planData.customeLogoBranding,
    modulesData
  ]);

  const handleModuleRemove = (moduleId) => {
    const updatedModules = selectedModules.filter(m => m.id !== moduleId);
  
    setSelectedModules(updatedModules);
    setPlanData(prev => ({
      ...prev,
      modules: updatedModules,
    }));
  };
  

  const addPros = () => {
    if (prosInput.trim()) {
      setPlanData(prev => ({
        ...prev,
        planPros: [...prev.planPros, prosInput.trim()]
      }));
      setProsInput("");
    }
  };

  const removePros = (index, isAutoGenerated = false) => {
    if (isAutoGenerated) {
      setAutoGeneratedPros(prev => prev.filter((_, i) => i !== index));
    } else {
      setPlanData(prev => ({
        ...prev,
        planPros: prev.planPros.filter((_, i) => i !== index)
      }));
    }
  };

  const addCons = () => {
    if (consInput.trim()) {
      setPlanData(prev => ({
        ...prev,
        planCons: [...prev.planCons, consInput.trim()]
      }));
      setConsInput("");
    }
  };

  const removeCons = (index, isAutoGenerated = false) => {
    if (isAutoGenerated) {
      setAutoGeneratedCons(prev => prev.filter((_, i) => i !== index));
    } else {
      setPlanData(prev => ({
        ...prev,
        planCons: prev.planCons.filter((_, i) => i !== index)
      }));
    }
  };

  // Calculate total price
  useEffect(() => {
    let total = parseFloat(planData.offerPrice) || 0;
    if (selectedModules.length > 0) {
      const modulePrices = selectedModules.reduce((sum, modulee) => {
        return sum + parseFloat(modulee.price || 0);
      }, 0);
      total += modulePrices;
    }
    setTotalPrice(total);
  }, [planData.offerPrice, selectedModules]);

  const handleSubmit = () => {
    const payload = {
      name: planData.name,
      code: planData.code,
      category: planData.category,
      status: planData.status, // Boolean: true for active, false for inactive
      description: planData.description,
      offerPrice: Number(planData.offerPrice),
      billingCycle: planData.billingCycle,
      gst: Number(planData.gst),
      maxStudent: Number(planData.maxStudent),
      maxStaffUser: Number(planData.maxStaffUser),
      storageLimit: planData.storageLimit,
      emailNotification: planData.emailNotification,
      smsAlerts: planData.smsAlerts,
      whatsappAlerts: planData.whatsappAlerts,
      customeLogoBranding: planData.customeLogoBranding,
      duration: planData.duration,
      termsAndPolicy: planData.termsAndPolicy,
      adminNotes: planData.adminNotes,
      modules: planData.modules,
      // Visual Fields
      icon: planData.icon,
      iconColor: planData.iconColor,
      planPros: [...autoGeneratedPros, ...planData.planPros],
      planCons: [...autoGeneratedCons, ...planData.planCons],
      // Flexible Plan Fields (only if category is flexible)
      ...(planData.category === "Flexible" && {
        perStudentPrice: Number(planData.perStudentPrice),
        minStudentLimit: Number(planData.minStudentLimit),
        maxStudentLimit: Number(planData.maxStudentLimit),
        creditCarryForward: planData.creditCarryForward,
      }),
    };

    console.log("Final Payload:", payload);
    if (isEditing) {
      addPlanMutation.mutate({ id: planId, payload });
    } else {
      addPlanMutation.mutate({ payload });
    }
  };

  // Show loading state while fetching plan data
  // if (isEditMode && planLoading) {
  //   return (
  //     <div className="flex justify-center items-center py-8">
  //       <div className="flex items-center gap-2 text-gray-600">
  //         <Icon icon="eos-icons:loading" className="text-2xl animate-spin" />
  //         <span>Loading plan data...</span>
  //       </div>
  //     </div>
  //   );
  // }

  // Show error state if plan data fetch failed
  if (isEditMode && planError) {
    return (
      <div className="flex justify-center items-center py-8">
        <div className="flex items-center gap-2 text-red-600">
          <Icon icon="mdi:alert-circle" className="text-2xl" />
          <span>Error loading plan: {planError.message}</span>
        </div>
      </div>
    );
  }

  return (
    <div>
      {!isEditing && (
      <HeadingHeader
        title="Add Plan"
        items={[
          { label: "Dashboard", path: "/" },
          { label: "Plan", path: "/plans/manage" },
          { label: "Add Plan", path: "/plans/add" },
        ]}
      />
      )}
      {isEditing && (
      <HeadingHeader
        title="Edit Plan"
        items={[
          { label: "Dashboard", path: "/" },
          { label: "Plan", path: "/plans/manage" },
          { label: "Edit Plan", path: `/plans/edit/${planId}` },
        ]}
      />
      )}

      <Card>
        {/* Section 1: Basic Plan Details */}
        <BorderedFieldset legend="Basic Plan Details">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <SlidingLabelInput
              type="text"
              label="Plan Name"
              placeholder="Free Trial, Starter, Premium"
              value={planData.name}
              onChange={(e) => handleChange("name", e.target.value)}
            />

            <SlidingLabelInput
              type="text"
              label="Plan Code"
              placeholder="e.g. FREE01"
              value={planData.code}
              onChange={(e) => handleChange("code", e.target.value)}
            />

            <SlidingLabelSelect
              label="Plan Category"
              value={planData.category}
              onChange={(e) => handleChange("category", e.target.value)}
            >
              <option value="">Select Category</option>
              <option value="Flexible">Flexible</option>
              <option value="Fixed">Fixed</option>
            </SlidingLabelSelect>

              <ToggleSwitch
              label="Plan Status"
              checked={planData.status}
              onChange={(val) => handleChange("status", val)}
            />
          </div>

          <div className="mt-4">
            <SlidingLabelInput
              type="textarea"
              label="Plan Description / Benefits"
              placeholder="Short summary of what this plan offers"
              value={planData.description}
              onChange={(e) => handleChange("description", e.target.value)}
            />
          </div>
        </BorderedFieldset>

        {/* Section 2: Visual Fields */}
        <BorderedFieldset legend="Visual Fields">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <SlidingLabelInput
              type="text"
              label="Icon (Iconify name)"
              placeholder="e.g. mdi:school"
              value={planData.icon}
              onChange={(e) => handleChange("icon", e.target.value)}
            />

            <SlidingColorInput
              label="Icon Color"
              name="iconColor"
              initialColor={planData.iconColor}
              onChange={(e) => handleChange("iconColor", e.target.value)}
            />

            <div className="flex items-center gap-2">
              {planData.icon && (
                <Icon 
                  icon={planData.icon} 
                  className="text-2xl" 
                  style={{ color: planData.iconColor }}
                />
              )}
              <span className="text-sm text-gray-500">Preview</span>
            </div>
          </div>
        </BorderedFieldset>

        {/* Section 3: Pricing & Billing */}
        <BorderedFieldset legend="Pricing & Billing">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <SlidingLabelInput
              type="number"
              label="Offer Price (INR)"
              placeholder="₹4999"
              value={planData.offerPrice}
              onChange={(e) => handleChange("offerPrice", e.target.value)}
            />

            <SlidingLabelSelect
              label="Billing Cycle"
              value={planData.billingCycle}
              onChange={(e) => handleChange("billingCycle", e.target.value)}
            >
              <option value="">Select</option>
              <option value="monthly">Monthly</option>
              <option value="quarterly">Quarterly</option>
              <option value="annually">Annually</option>
            </SlidingLabelSelect>

            <SlidingLabelInput
              type="number"
              label="GST %"
              placeholder="18"
              value={planData.gst}
              onChange={(e) => handleChange("gst", e.target.value)}
            />
          </div>

          {/* Flexible Plan Pricing */}
          {planData.category === "Flexible" && (
            <div className="mt-6 p-4 bg-blue-50 rounded-lg">
              <h4 className="text-lg font-semibold text-blue-800 mb-4">Flexible Plan Pricing</h4>
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <SlidingLabelInput
                  type="number"
                  label="Per Student Price (INR)"
                  placeholder="₹100"
                  value={planData.perStudentPrice}
                  onChange={(e) => handleChange("perStudentPrice", e.target.value)}
                />

                <SlidingLabelInput
                  type="number"
                  label="Min Student Limit"
                  placeholder="10"
                  value={planData.minStudentLimit}
                  onChange={(e) => handleChange("minStudentLimit", e.target.value)}
                />

                <SlidingLabelInput
                  type="number"
                  label="Max Student Limit"
                  placeholder="1000"
                  value={planData.maxStudentLimit}
                  onChange={(e) => handleChange("maxStudentLimit", e.target.value)}
                />

                <div className="flex items-center">
                  <ToggleSwitch
                    label="Credit Carry Forward"
                    checked={planData.creditCarryForward}
                    onChange={(val) => handleChange("creditCarryForward", val)}
                  />
                </div>
              </div>
            </div>
          )}

          {/* Fixed Plan Pricing */}
          {planData.category === "Fixed" && (
            <div className="mt-6 p-4 bg-green-50 rounded-lg">
              <h4 className="text-lg font-semibold text-green-800 mb-4">Fixed Plan Limits</h4>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <SlidingLabelInput
              type="number"
              label="Max Students"
                  placeholder="500"
              value={planData.maxStudent}
              onChange={(e) => handleChange("maxStudent", e.target.value)}
            />

            <SlidingLabelInput
              type="number"
              label="Max Staff Users"
                  placeholder="50"
              value={planData.maxStaffUser}
              onChange={(e) => handleChange("maxStaffUser", e.target.value)}
            />

            <SlidingLabelInput
                  type="text"
                  label="Storage Limit"
                  placeholder="10GB"
              value={planData.storageLimit}
              onChange={(e) => handleChange("storageLimit", e.target.value)}
            />
          </div>
            </div>
          )}
        </BorderedFieldset>

        {/* Section 4: Module Selection */}
        <BorderedFieldset legend="Included Modules">
          <div className="mb-4">
            <SlidingLabelSelect
              label="Select Module"
              value=""
              onChange={(e) => handleModuleSelect(e.target.value)}
            >
              <option value="">Select a module to add</option>
              {modulesData?.data?.map((mod) => (
                <option key={mod.id} value={mod.id}>
                  {mod.name} - ₹{mod.price || 0}
              </option>
              ))}
            </SlidingLabelSelect>
          </div>

          {/* Selected Modules */}
          {selectedModules.length > 0 && (
            <div className="mt-4">
              <h4 className="text-sm font-medium text-gray-700 mb-2">Selected Modules:</h4>
              <div className="space-y-2">
                {selectedModules.map((modulee) => (
                  <div key={modulee.id} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                    <div className="flex items-center gap-3">
                      <span className="font-medium">{modulee.name}</span>
                      <span className="text-sm text-gray-500">₹{modulee.price || 0}</span>
                    </div>
                    <button
                      type="button"
                      onClick={() => handleModuleRemove(modulee.id)}
                      className="bg-red-500 hover:bg-red-700 p-1 cursor-pointer rounded-sm text-white"
                    >
                      <Icon icon="weui:delete-on-filled" className="w-4 h-4" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Total Price Display */}
          <div className="mt-4 p-4 bg-yellow-50 rounded-lg">
            <div className="flex justify-between items-center">
              <span className="font-semibold text-gray-700">Total Plan Price:</span>
              <span className="text-2xl font-bold text-yellow-600">₹{totalPrice}</span>
            </div>
            <div className="text-sm text-gray-500 mt-1">
              Base Price: ₹{planData.offerPrice || 0} + Module Prices: ₹{totalPrice - (planData.offerPrice || 0)}
            </div>
          </div>
        </BorderedFieldset>

        {/* Section 5: Plan Pros & Cons */}
        <BorderedFieldset legend="Plan Pros & Cons">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Pros */}
            <div>
              <h4 className="text-sm font-medium text-gray-700 mb-2">Plan Pros</h4>
              
              {/* Auto-generated Pros */}
              {autoGeneratedPros.length > 0 && (
                <div className="mb-4">
                  <h5 className="text-xs font-medium text-blue-600 mb-2">Auto-generated based on modules & plan type:</h5>
                  <div className="space-y-1">
                    {autoGeneratedPros.map((pro, index) => (
                      <div key={`auto-pro-${index}`} className="flex items-center justify-between p-2 bg-blue-50 rounded border-l-4 border-blue-400">
                        <span className="text-sm">✓ {pro}</span>
                        <button
                          type="button"
                          onClick={() => removePros(index, true)}
                          title="Remove auto-generated pro"
                          className="bg-red-500 hover:bg-red-700 p-1 cursor-pointer rounded-sm text-white"
                          >
                            <Icon icon="mdi:close" className="w-4 h-4" />
                          </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Custom Pros */}
              <div className="mb-2">
                <h5 className="text-xs font-medium text-green-600 mb-2">Custom pros:</h5>
                <div className="flex gap-2 mb-2">
                  <input
                    type="text"
                    value={prosInput}
                    onChange={(e) => setProsInput(e.target.value)}
                    placeholder="Add a custom pro..."
                    className="flex-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-500"
                    onKeyPress={(e) => e.key === 'Enter' && addPros()}
                  />
                  <button
                    type="button"
                    onClick={addPros}
                    className="px-4 py-2 cursor-pointer bg-green-500 text-white rounded-md hover:bg-green-600"
                  >
                    Add
                  </button>
                </div>
                <div className="space-y-1">
                  {planData.planPros.map((pro, index) => (
                    <div key={`custom-pro-${index}`} className="flex items-center justify-between p-2 bg-green-50 rounded border-l-4 border-green-400">
                      <span className="text-sm">✓ {pro}</span>
                      <button
                        type="button"
                        onClick={() => removePros(index, false)}
                        title="Remove custom pro"
                        className="bg-red-500 hover:bg-red-700 p-1 cursor-pointer rounded-sm text-white"
                        >
                          <Icon icon="mdi:close" className="w-4 h-4" />
                        </button>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Cons */}
            <div>
              <h4 className="text-sm font-medium text-gray-700 mb-2">Plan Cons</h4>
              
              {/* Auto-generated Cons */}
              {autoGeneratedCons.length > 0 && (
                <div className="mb-4">
                  <h5 className="text-xs font-medium text-orange-600 mb-2">Auto-generated based on modules & plan type:</h5>
                  <div className="space-y-1">
                    {autoGeneratedCons.map((con, index) => (
                      <div key={`auto-con-${index}`} className="flex items-center justify-between p-2 bg-orange-50 rounded border-l-4 border-orange-400">
                        <span className="text-sm">✗ {con}</span>
                        <button
                          type="button"
                          onClick={() => removeCons(index, true)}
                          title="Remove auto-generated con"
                          className="bg-red-500 hover:bg-red-700 p-1 cursor-pointer rounded-sm text-white"
                          >
                            <Icon icon="mdi:close" className="w-4 h-4" />
                          </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Custom Cons */}
              <div className="mb-2">
                <h5 className="text-xs font-medium text-red-600 mb-2">Custom cons:</h5>
                <div className="flex gap-2 mb-2">
                  <input
                    type="text"
                    value={consInput}
                    onChange={(e) => setConsInput(e.target.value)}
                    placeholder="Add a custom con..."
                    className="flex-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-red-500"
                    onKeyPress={(e) => e.key === 'Enter' && addCons()}
                  />
                  <button
                    type="button"
                    onClick={addCons}
                    className="px-4 py-2 bg-red-500 text-white rounded-md hover:bg-red-600"
                  >
                    Add
                  </button>
                </div>
                <div className="space-y-1">
                  {planData.planCons.map((con, index) => (
                    <div key={`custom-con-${index}`} className="flex items-center justify-between p-2 bg-red-50 rounded border-l-4 border-red-400">
                      <span className="text-sm">✗ {con}</span>
                      <button
                        type="button"
                        onClick={() => removeCons(index, false)}
                        className="bg-red-500  hover:bg-red-700 p-1 cursor-pointer rounded-sm text-white"
                        title="Remove custom con"
                      >
                        <Icon icon="mdi:close" className="w-4 h-4" />
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </BorderedFieldset>

        {/* Section 6: Notifications & Branding */}
        <BorderedFieldset legend="Notifications & Branding">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <ToggleSwitch
              label="Email Notifications"
              checked={planData.emailNotification}
              onChange={(val) => handleChange("emailNotification", val)}
            />

            <ToggleSwitch
              label="SMS Alerts"
              checked={planData.smsAlerts}
              onChange={(val) => handleChange("smsAlerts", val)}
            />

            <ToggleSwitch
              label="WhatsApp Alerts"
              checked={planData.whatsappAlerts}
              onChange={(val) => handleChange("whatsappAlerts", val)}
            />

            <ToggleSwitch
              label="Custom Logo Branding"
              checked={planData.customeLogoBranding}
              onChange={(val) => handleChange("customeLogoBranding", val)}
            />
          </div>
        </BorderedFieldset>

        {/* Section 7: Notes & Controls */}
        <BorderedFieldset legend="Notes & Controls">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <SlidingLabelSelect
              label="Plan Duration"
              value={planData.duration}
              onChange={(e) => handleChange("duration", e.target.value)}
            >
              <option value="">Select Duration</option>
              <option value="7days">7 Days</option>
              <option value="30days">30 Days</option>
              <option value="90days">90 Days</option>
              <option value="1year">1 Year</option>
            </SlidingLabelSelect>

            <SlidingLabelInput
              type="text"
              label="Terms & Policy Link"
              placeholder="https://yourdomain.com/terms"
              value={planData.termsAndPolicy}
              onChange={(e) => handleChange("termsAndPolicy", e.target.value)}
            />
          </div>

          <div className="mt-4">
            <SlidingLabelInput
              type="textarea"
              label="Admin Notes"
              placeholder="Internal note for your SaaS team"
              value={planData.adminNotes}
              onChange={(e) => handleChange("adminNotes", e.target.value)}
            />
          </div>
        </BorderedFieldset>

        {/* Submit Button */}
        <div className="mt-8 text-right">
          <button
            onClick={handleSubmit}
            disabled={addPlanMutation.isLoading}
            className="bg-indigo-500 cursor-pointer text-white px-6 py-2 rounded-lg hover:bg-indigo-700 disabled:opacity-50"
          >
            {addPlanMutation.isLoading ? (isEditing ? "Updating..." : "Saving...") : (isEditing ? "Update Plan" : "Save Plan")}
          </button>
        </div>
      </Card>
    </div>
  );
};

export default AddPlan;
